### ISSUE TITLE
LET'S DO THIS!

### ISSUE THREAD

**Issue by araujolma** [ronaldochaves/rprtAutomator#2]
Hey @ronaldochaves ! 

I have been getting inputs from both my bosses (that is, from both sides) that we should have already implemented this. Besides, since the SOAR project seems to be walking on its own, I think I should start going deeper into this project.

I should warn you, though, there are **MAJOR** expectations here! I want to organize this further, and use the same core program to several use cases (Basic flow check in 20kN, GG, SSTC, H1, L5, FuelPump, Turbine, TheDevilInBoots, etc). Of course, the reports (memotecs) would be way simpler than the GG ones (a product of the joint venture with Iago/"Godin"), but that was much more focused in _analysing_ the test data (hence making the future, campaign report, easier) than merely _documenting_ the test itself. 

My goal is to write a program that is as simple as possible, but robust enough to be valid to a huge ammount of situations, with focus on presenting simple and immediate information to the clients.

What do you think?

**Comment by ronaldochaves** [comment]
Hooop!

That's such a brilliant idea, @araujolma. Actually, I have talked to your X-Boss and selled the idea to automatize **HX** test reports, since I was (am) very excited in this project.

Since the structure of a TDMS file is already defined, it is totally feasible to automitize all TheDevilInBoots reports, making it simpler in an initial approach. I see one problem here that is which varibles should be plotted based on the test kind or client needs, but it is not a big deal since we can do it hard coded in this approach.

For the latter approach, taking into account the robustness of the program, we need a **standardization** of the metadata of the test. I think it is going to be the biggest problem for us, but of couse we can overcome this.

Let's *stick in the machine*!!
